# Generated by Django 3.2.18 on 2023-03-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoltajeCorriente',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('voltaje', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('corriente', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
            ],
        ),
    ]
